autoscaling:
  enabled: true
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: miraccan/myargodjangotest
  tag: 1.0.0
nameOverride: ''
replicaCount: 1
service:
  port: 80
  targetPort: 8000
  NodePort: 30005
