autoscaling:
  enabled: true
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
fullnameOverride: ''
db:
  name: dGVzdAo=
  user: dGVzdAo=
  password: dGVzdAo=
  host: cG9zdGdyZXMK
image:
  pullPolicy: IfNotPresent
  repository: miraccan/servicename
  tag: 1.0.7
nameOverride: ''
replicaCount: 1
service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 32001
