product:
  name: fitness-app
  description: "Fitness application for tracking workouts and meals"
  category: "Health & Fitness"
  tags:
    - "fitness"
    - "health"
    - "workout"
    - "meal"

service:
  name: "workout-service"
  type: "Api" # Api | Gateway | UI
  language: "Python" # Python | NodeJs | Java | Go | Other
  framework: "Django" # Django | Flask | FastAPI | Express | Other
  version: "1.0.0"