apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOGLEVEL: "info"
  DEBUG: "True"
  DATABASE_ENGINE: "postgresql_psycopg2"
  DBNAME: 'test'
  DBHOST: 'postgresql'
  DBPORT: '5432'