apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "djangoapp.name" . }}-deployment
  namespace: {{ .Values.namespace }}
  annotations:
    checksum/config: "{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "djangoapp.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ include "djangoapp.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
          - configMapRef:
              name: {{ include "djangoapp.name" . }}-configmap
          - secretRef:
              name: {{ include "djangoapp.name" . }}-secret
          resources:
            requests:
              memory: "512Mi" 
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
