apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "djangoapp.name" .}}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "djangoapp.name" .}}-service
            port:
              number: 80