apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-django-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: miraccanyilmaz.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "djangoapp.name" .}}-service
                port:
                  number: {{ .Values.service.port }}