apiVersion: v1
kind: Secret
metadata:
  name: {{ include "djangoapp.name" . }}-secret
data:
    DB_NAME: {{ .Values.db.name | b64dec | quote }}
    DB_USER: {{ .Values.db.user | b64dec | quote }}
    DB_PASSWORD: {{ .Values.db.password | b64dec | quote }}
    DB_HOST: {{ .Values.db.host | b64dec | quote }}
    