apiVersion: v1
kind: Service
metadata:
  name: {{ include "djangoapp.name" .}}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "djangoapp.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.targetPort }}
      # nodePort: 31500