name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Read version and appName from applicationmanifest.yaml
      id: read_manifest
      uses: einaregilsson/parse-yaml@v1
      with:
        file: "applicationmanifest.yaml"
    
    - name: Build and Push Docker Image
      run: |
        version=${{ steps.read_manifest.outputs.version }}
        appName=${{ steps.read_manifest.outputs.appName }}
        
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ appName }}:${{ version }} ./${{ appName }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ appName }}:${{ version }}