name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      SERVICE_NAME: 'servicename'
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Read version from applicationmanifest.yaml
      id: read_version
      uses: einaregilsson/parse-yaml@v1
      with:
        file: "applicationmanifest.yaml"
    
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.read_version.outputs.version }} ./${{ env.SERVICE_NAME }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.read_version.outputs.version }}
