name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      SERVICE_NAME: 'servicename'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq -y
        sudo apt-get update -q
        sudo apt-get install yq -y
    - name: Get Version from application-manifest.yaml
      id: get_version
      run: |
        export VERSION=$(yq eval '.version' application-manifest.yaml)
        echo "Version: $VERSION"
        echo "::set-output name=version::$VERSION"
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.get_version.outputs.version }} ./${{ env.SERVICE_NAME }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.get_version.outputs.version }}
    # - name: Commit and Push Changes
    #   run: argocd app set djangoargo -p image.tag=${{ steps.get_version.outputs.version }}