on:
  push:
    branches:
      - master
    paths:
      - 'servicename/**'

jobs:
  build-sign-and-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      SERVICE_NAME: 'servicename'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install yq
      run: |
        sudo apt-get update -q
        sudo apt-get install python3-pip -y
        pip3 install yq

    - name: Get Version from application-manifest.yaml
      id: get_version
      run: |
        export VERSION=$(yq eval '.version' application-manifest.yaml)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version: $VERSION"

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }} ./${{ env.SERVICE_NAME }}

    - name: Push Signed Docker Image
      run: |
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}