name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      SERVİCE_NAME: servicename
      VERSION: 1.0.0
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Read version and appName from applicationmanifest.yaml
      run: |
        version=$(python3 -c "import yaml; f=open('applicationmanifest.yaml'); data=yaml.safe_load(f); print(data['version'])")
        appName=$(python3 -c "import yaml; f=open('applicationmanifest.yaml'); data=yaml.safe_load(f); print(data['appName'])")
        
        echo "Version: $version"
        echo "App Name: $appName"
    
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ appName }}:${{ version }} ./${{ appName }}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ appName }}:${{ version }}