on:
  push:
    branches:
      - master
    paths:
      - 'servicename/**'

jobs:
  build-sign-and-publish:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      SERVICE_NAME: 'servicename'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install yq
      run: |
        sudo apt-get update -q
        sudo apt-get install -y yq

    - name: Generate Version Number
      id: get_version
      run: |
        BUILD_NUMBER=${{ github.run_number }}
        VERSION="1.0.${BUILD_NUMBER}"  # Example format: 1.0.1234
        echo "Generated Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }} ./${{ env.SERVICE_NAME }}

    - name: Push Signed Docker Image
      run: |
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}