name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Read version and appName from applicationmanifest.yaml
      run: |
        version=$(cat applicationmanifest.yaml | grep "version:" | awk '{print $2}')
        appName=$(cat applicationmanifest.yaml | grep "appName:" | awk '{print $2}')
        
        echo "Version: $version"
        echo "App Name: $appName"
    
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ appName }}:${{ version }} ./${{ appName }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ appName }}:${{ version }}