affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
db:
  host: postgres
  name: postgres
  password: postgres
  user: postgres
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: microservicename
  tag: 1.0.0
imagePullSecrets: []
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  className: nginx
  enabled: false
  hosts:
  - host: miraccanyilmaz.localhost
    paths:
    - path: /
      pathType: ImplementationSpecific
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 8000
  targetPort: 8000
  type: LoadBalancer
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []
